apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: cicd-first
build:
  tagPolicy:
    gitCommit: {}
  local: {}
manifests:
  rawYaml:
    - ./kubernetes/app1.yaml
    - ./kubernetes/app2.yaml
deploy:
  kubeContext: gke_my-devops-cicd_us-central1_gke-cluster-1
  kubectl:
    manifests:
      - ./kubernetes/app1.yaml
      - ./kubernetes/app2.yaml
  logs:
    prefix: container

profiles:
  - name: prod
    activation:
      - kubeContext: gke_my-devops-cicd_us-central1_gke-cluster-2
    deploy:
      kubeContext: gke_my-devops-cicd_us-central1_gke-cluster-2
      kubectl:
        manifests:
          - ./kubernetes/app1.yaml
          - ./kubernetes/app2.yaml