apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: cicd-first
build:
  tagPolicy:
    gitCommit: {}
  local: {}
manifests:
  rawYaml:
    - ./kubernetes/app1.yaml
    - ./kubernetes/app2.yaml
deploy:
  kubectl: {
    kubeContext: gke_cicd-first_us-central1_cluster-1
    }
  logs:
    prefix: container

profiles:
  - name: prod
    activation:
      - kubeContext: gke_cicd-first_us-central1_cluster-2
    deploy:
      kubectl:
        kubeContext: gke_cicd-first_us-central1_cluster-2